name: the_big_thing
description: A Days-Matter-Like app written in flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.0
    velocity_x: ^1.3.1
    get:
    table_calendar: ^2.3.3
    hive: ^1.4.4+1
    hive_flutter: ^0.3.1
    flutter_local_notifications: ^3.0.2
    flutter_colorpicker: ^0.3.4
    just_audio: ^0.6.4
    flutter_search_bar: ^2.1.0
    file_picker: ^2.1.4
    floor: ^0.18.0
    dio: ^3.0.10
    timezone: ^0.5.9
    qr_code_scanner: ^0.2.1
    flutter_sound: ^7.4.13+3
    home_widget: ^0.0.1+2
    qr_flutter:
        git:
            url: git://github.com/lukef/qr.flutter.git
dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^0.8.2
    flutter_launcher_icons: '^0.8.0'
    floor_generator: ^0.18.0
    build_runner: ^1.10.11

flutter_icons:
    android: 'launcher_icon'
    ios: false
    image_path: 'assets/launcher_icon.png'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    assets:
        - assets/sketch.jpg
        - assets/sketch-folder.jpg
    fonts:
        - family: SourceHanSerifCN
          fonts:
              - asset: assets/fonts/SourceHanSerifCN-Medium.ttf
              - asset: assets/fonts/SourceHanSerifCN-Bold.ttf
              - asset: assets/fonts/SourceHanSerifCN-Heavy.ttf
    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
